backend:
  name: github
  repo: qc-web-and-mobile/local-business-support
media_folder_relative: true
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
collections:
  - name: businesses
    label: Businesses
    media_folder: ""
    public_folder: ""
    folder: content/businesses
    create: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "city", label: "City" }
      - { name: "cover", label: "Cover Photo", widget: "image" }
      - { name: "path", label: "URL Path" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "tags",
          label: "Tags",
          widget: "list",
          default: ["Curbside", "Drive Thru", "Delivery", "Carry Out"],
        }
