backend:
  name: github
  repo: qc-web-and-mobile/local-business-support
media_folder_relative: true
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
collections:
  - name: businesses
    label: Businesses
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    folder: content/businesses
    create: true
    fields:
      - { name: "title", label: "Title" }
      - {
          name: "city",
          label: "Select a City",
          widget: "select",
          options:
            ["Davenport", "Bettendorf", "Rock Island", "Moline", "East Moline"],
        }
      - { name: "cover", label: "Cover Photo", widget: "image" }
      - {
          name: "path",
          label: "URL Path",
          hint: 'If a store is "Hello Deli", the url should be something like /hello-deli',
        }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "tags",
          label: "Supported Ordering Options",
          widget: "select",
          options: ["Curbside", "Drive Thru", "Delivery", "Carry Out"],
          multiple: true,
          default: ["Curbside", "Drive Thru", "Delivery", "Carry Out"],
        }
      - { name: "body", label: "Body", widget: "markdown" }
